# Generated by Django 4.2.6 on 2023-12-09 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0002_vendor_vendor_code'),
        ('vehicle1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrecieve',
            name='vendorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendor.vendor'),
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
