# Generated by Django 4.2.6 on 2023-12-09 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclepermit',
            name='vehicle_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle1.vehicle'),
        ),
    ]
