# Generated by Django 4.2.6 on 2023-12-12 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle1', '0002_vehiclepermit_vehicle_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiclePollution',
            fields=[
                ('pollution_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_pollution_from_Date', models.DateField()),
                ('vehicle_pollution_to_Date', models.DateField()),
                ('vehicle_pollution_value', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('lastModifiedOn', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_pollution_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_pollution_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_pollution_modify_by', to=settings.AUTH_USER_MODEL)),
                ('vehicle_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle1.vehicle')),
            ],
        ),
    ]
