# Generated by Django 4.2.6 on 2023-12-13 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle1', '0003_vehiclepollution'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleTax',
            fields=[
                ('tax_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_tax_from_Date', models.DateField()),
                ('vehicle_tax_to_Date', models.DateField()),
                ('vehicle_tax_type', models.CharField(max_length=255)),
                ('vehicle_environment_tax', models.DecimalField(decimal_places=2, max_digits=30)),
                ('vehicle_professional_tax', models.DecimalField(decimal_places=2, max_digits=30)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('lastModifiedOn', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_tax_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_tax_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_tax_modify_by', to=settings.AUTH_USER_MODEL)),
                ('vehicle_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle1.vehicle')),
            ],
        ),
    ]
