# Generated by Django 4.2.6 on 2024-01-02 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('collection_id', models.AutoField(primary_key=True, serialize=False)),
                ('collection_date', models.DateField(null=True)),
                ('collection_time', models.TimeField(null=True)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=20, null=True)),
                ('longtitude', models.DecimalField(decimal_places=5, max_digits=20, null=True)),
                ('total_amount', models.FloatField()),
                ('collections_status', models.CharField(default='0', max_length=10)),
                ('fanialize_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Collection',
            },
        ),
        migrations.CreateModel(
            name='CollectionMode',
            fields=[
                ('collection_mode_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_mode', models.CharField(max_length=100)),
                ('payment_amount', models.FloatField()),
                ('upload_image', models.FileField(blank=True, max_length=2000, null=True, upload_to='collection/all_collections/')),
            ],
            options={
                'db_table': 'CollectionMode',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint_date', models.DateField(null=True)),
                ('complaint_time', models.TimeField(null=True)),
                ('approve_yn', models.CharField(max_length=50)),
                ('remark', models.TextField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Complaint',
            },
        ),
        migrations.CreateModel(
            name='SkipShop',
            fields=[
                ('skip_shop_id', models.AutoField(primary_key=True, serialize=False)),
                ('skip_shop_date', models.DateField(null=True)),
                ('skip_shop_time', models.TimeField(null=True)),
                ('approve_yn', models.CharField(max_length=50)),
                ('remark', models.TextField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('approve_byId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cashierId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SkipShop_cashier_Id', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SkipShop_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SkipShop_last_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SkipShop',
            },
        ),
    ]
