# Generated by Django 4.2.6 on 2024-01-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionmode',
            name='OTP',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
