# Generated by Django 4.2.6 on 2024-01-02 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('asset', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assetpurchase',
            name='vendor_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendor.vendor'),
        ),
        migrations.AddField(
            model_name='assetdistribution',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AssetsDistribution_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetdistribution',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AssetsDistribution_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetdistribution',
            name='last_modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AssetsDistribution_last_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetdistribution',
            name='user_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
    ]
