# Generated by Django 4.2.6 on 2023-12-20 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetdistribution',
            name='user_roll_id',
        ),
        migrations.AddField(
            model_name='assetdistribution',
            name='user_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='long_lasting_products',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='assets',
            name='slowly_finished_product',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
