# Generated by Django 4.2.6 on 2023-12-20 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_remove_assetdistribution_user_roll_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetdistribution',
            old_name='assets_cunsumer_type',
            new_name='assets_consumer_type',
        ),
    ]
