# Generated by Django 4.2.6 on 2024-01-02 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor1', '0002_alter_vendor_table_alter_vendorcreditbalance_table_and_more'),
        ('asset', '0003_rename_assets_cunsumer_type_assetdistribution_assets_consumer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetpurchase',
            name='vendor_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendor1.vendor'),
        ),
        migrations.AlterModelTable(
            name='assetdistribution',
            table='AssetDistribution',
        ),
        migrations.AlterModelTable(
            name='assetpurchase',
            table='AssetPurchase',
        ),
        migrations.AlterModelTable(
            name='assets',
            table='Assets',
        ),
        migrations.AlterModelTable(
            name='assetstock',
            table='AssetStock',
        ),
    ]
