# Generated by Django 4.2.6 on 2024-01-02 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='routemodel',
            table='RouteModel',
        ),
    ]
