# Generated by Django 4.2.6 on 2023-12-01 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicalMakeBy',
            fields=[
                ('vehical_make_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehical_make_by', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_make_by',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_make_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.vehicalmakeby'),
        ),
    ]
