# Generated by Django 4.2.6 on 2024-01-02 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vendor',
            table='Vendor',
        ),
        migrations.AlterModelTable(
            name='vendorcreditbalance',
            table='VendorCreditBalance',
        ),
        migrations.AlterModelTable(
            name='vendoropeningbalance',
            table='VendorOpeningBalance',
        ),
        migrations.AlterModelTable(
            name='vendorproduct',
            table='VendorProduct',
        ),
    ]
