# Generated by Django 4.2.6 on 2023-11-03 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopRoute',
            fields=[
                ('shop_route_id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_order', models.CharField(max_length=10, null=True)),
                ('route_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.routemodel')),
                ('shop_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shopmodel')),
            ],
        ),
    ]
