# Generated by Django 4.2.6 on 2024-01-02 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
        ('vehicle', '0001_initial'),
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productrecieve',
            name='vendorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendor.vendor'),
        ),
        migrations.AddField(
            model_name='productmaster',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_master_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productmaster',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_master_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productmaster',
            name='last_modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_master_last_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productmaster',
            name='product_categoryId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.productcategories'),
        ),
        migrations.AddField(
            model_name='productmaster',
            name='product_typeId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.producttypes'),
        ),
        migrations.AddField(
            model_name='productissue',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ProductIssue_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productissue',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ProductIssue_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productissue',
            name='driverId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productissue',
            name='last_modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ProductIssue_last_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productissue',
            name='product_typeId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.producttypes'),
        ),
        migrations.AddField(
            model_name='productissue',
            name='shopId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shopmodel'),
        ),
        migrations.AddField(
            model_name='productissue',
            name='vehicleId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.vehicle'),
        ),
    ]
