# Generated by Django 4.2.5 on 2024-01-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproductrequest',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
