# Generated by Django 4.2.6 on 2023-11-29 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_productcategories_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='associations',
            old_name='association_equence',
            new_name='association_sequence',
        ),
    ]
