# Generated by Django 4.2.6 on 2023-12-06 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0005_rename_association_equence_associations_association_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopRate',
            fields=[
                ('shop_rate_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_rate', models.FloatField(default=0)),
                ('product_formula', models.FloatField(default=0)),
                ('flexible_rate_yn', models.CharField(default='No', max_length=15, null=True)),
                ('rate_active_yn', models.CharField(default='No', max_length=15, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('associationId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.associations')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ShopRates_rates_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ShopRates_rates_last_modified', to=settings.AUTH_USER_MODEL)),
                ('product_typeId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.producttypes')),
                ('shopId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shopmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ShopFlexibleRate',
            fields=[
                ('shop_flexible_rate_id', models.AutoField(primary_key=True, serialize=False)),
                ('flexible_rate_date', models.DateField()),
                ('flexible_rate', models.FloatField()),
                ('flexible_formula', models.IntegerField(null=True)),
                ('sell_rate', models.FloatField()),
                ('with_skin', models.FloatField()),
                ('without_skin', models.FloatField()),
                ('sms_send_yn', models.CharField(default='No', max_length=15, null=True)),
                ('sms_replyId', models.IntegerField(null=True)),
                ('product_typeId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.producttypes')),
                ('shopId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shopmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ShopBalance',
            fields=[
                ('shop_balance_id', models.AutoField(primary_key=True, serialize=False)),
                ('balance_date', models.DateField()),
                ('balance', models.FloatField()),
                ('active', models.CharField(default='Yes', max_length=15, null=True)),
                ('adjustment_amount', models.FloatField(null=True)),
                ('adjustment_remark', models.TextField(null=True)),
                ('balance_utc_date', models.DateTimeField(auto_now_add=True)),
                ('shopId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shopmodel')),
            ],
        ),
    ]
