# Generated by Django 4.2.6 on 2023-12-07 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0006_shoprate_shopflexiblerate_shopbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopbalance',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_balance_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shopbalance',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shopbalance',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_balance_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shopbalance',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopbalance',
            name='last_modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_balance_last_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shopbalance',
            name='last_modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shopflexiblerate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_flexible_rate_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shopflexiblerate',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shopflexiblerate',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_flexible_rate_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shopflexiblerate',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopflexiblerate',
            name='last_modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_flexible_rate_last_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shopflexiblerate',
            name='last_modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='ShopRate',
        ),
    ]
