# Generated by Django 4.2.6 on 2023-12-06 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrecieve',
            name='latitude',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='productrecieve',
            name='longtitude',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
        migrations.CreateModel(
            name='Fitness',
            fields=[
                ('fitness_id', models.AutoField(primary_key=True, serialize=False)),
                ('registration_no', models.CharField(max_length=50)),
                ('vehicle_fitness_from_date', models.DateField()),
                ('vehicle_fitness_to_date', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_fitness_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_fitness_modify_by', to=settings.AUTH_USER_MODEL)),
                ('vehicle_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle_app.vehicle')),
            ],
        ),
    ]
