# Generated by Django 4.2.6 on 2023-12-07 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0005_rename_association_equence_associations_association_sequence'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleMakeBy',
            fields=[
                ('vehicle_make_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_make_by', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('vehicle_model_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_model', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('vehicle_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=150)),
                ('vendor_type', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('registration_no', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=100)),
                ('vehicle_details', models.CharField(max_length=200)),
                ('fuel_type', models.CharField(max_length=50)),
                ('no_of_wheel', models.IntegerField()),
                ('carrier_type', models.CharField(max_length=100)),
                ('registration_date', models.DateField()),
                ('vehicle_make_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehiclemakeby')),
                ('vehicle_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehiclemodel')),
                ('vehicle_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicletype')),
            ],
        ),
        migrations.CreateModel(
            name='ProductRecieve',
            fields=[
                ('product_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('recieved_date', models.DateTimeField(null=True)),
                ('paper_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recieved_quantity', models.IntegerField()),
                ('recieved_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tcs_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tcs_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('recieved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('source_vehicle_id', models.IntegerField()),
                ('source_driver_id', models.IntegerField()),
                ('challan_no', models.CharField(max_length=150)),
                ('entry_source', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=20, null=True)),
                ('longtitude', models.DecimalField(decimal_places=5, max_digits=20, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('delete_reason', models.CharField(max_length=150)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_received_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_received_deleted', to=settings.AUTH_USER_MODEL)),
                ('driverId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.usermodel')),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_received_last_modified', to=settings.AUTH_USER_MODEL)),
                ('productId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.productmaster')),
                ('product_typeId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.producttypes')),
                ('vehicleId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicle')),
                ('vendorId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Fitness',
            fields=[
                ('fitness_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_fitness_from_date', models.DateField()),
                ('vehicle_fitness_to_date', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_fitness_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fitness_details_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_fitness_modify_by', to=settings.AUTH_USER_MODEL)),
                ('vehicle_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicle')),
            ],
        ),
    ]
