# Generated by Django 4.2.6 on 2023-12-08 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiclePermit',
            fields=[
                ('permit_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_permit_from_Date', models.DateField()),
                ('vehicle_permit_to_Date', models.DateField()),
                ('vehicle_permit_type', models.CharField(max_length=255)),
                ('vehicle_permit_id', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('lastModifiedOn', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_permit_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_permit_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_permit_modify_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleInsurance',
            fields=[
                ('insurance_id', models.AutoField(primary_key=True, serialize=False)),
                ('insurance_company', models.CharField(max_length=255)),
                ('insurance_from_Date', models.DateField()),
                ('insurance_to_date', models.DateField()),
                ('insurance_amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('insurance_paid_mount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('lastModifiedOn', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_insurance_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_insurance_details_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_insurance_modify_by', to=settings.AUTH_USER_MODEL)),
                ('vehicle_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicle')),
            ],
        ),
    ]
