# Generated by Django 4.2.6 on 2023-12-14 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_usermodel_user_role'),
        ('shops1', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('collection_id', models.AutoField(primary_key=True, serialize=False)),
                ('collection_date', models.DateField(null=True)),
                ('collection_time', models.TimeField(null=True)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=20, null=True)),
                ('longtitude', models.DecimalField(decimal_places=5, max_digits=20, null=True)),
                ('total_amount', models.FloatField()),
                ('fanialize_on', models.DateTimeField(auto_now=True)),
                ('cashierId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.usermodel')),
                ('fanialize_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shopId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops1.shopmodel')),
            ],
        ),
        migrations.CreateModel(
            name='SkipShop',
            fields=[
                ('skip_shop_id', models.AutoField(primary_key=True, serialize=False)),
                ('skip_shop_date', models.DateField(null=True)),
                ('skip_shop_time', models.TimeField(null=True)),
                ('approve_yn', models.CharField(max_length=50)),
                ('remark', models.TextField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('approve_byId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cashierId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.usermodel')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SkipShop_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SkipShop_last_modified_by', to=settings.AUTH_USER_MODEL)),
                ('shopId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops1.shopmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionMode',
            fields=[
                ('collection_mode_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_mode', models.CharField(max_length=100)),
                ('payment_amount', models.FloatField()),
                ('collectionId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection_api.collection')),
            ],
        ),
    ]
