# Generated by Django 4.2.6 on 2023-12-15 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='cashierId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_cashier_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='skipshop',
            name='cashierId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SkipShop_cashier_Id', to=settings.AUTH_USER_MODEL),
        ),
    ]
