# Generated by Django 4.2.6 on 2023-12-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_api', '0002_alter_collection_cashierid_alter_skipshop_cashierid'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionmode',
            name='upload_image',
            field=models.FileField(blank=True, max_length=2000, null=True, upload_to='s3://kukudku/collection'),
        ),
    ]
