# Generated by Django 4.2.6 on 2023-12-18 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops1', '0001_initial'),
        ('collection_api', '0003_collectionmode_upload_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionmode',
            name='upload_image',
            field=models.FileField(blank=True, max_length=2000, null=True, upload_to='collection/all_collections/'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint_date', models.DateField(null=True)),
                ('complaint_time', models.TimeField(null=True)),
                ('approve_yn', models.CharField(max_length=50)),
                ('remark', models.TextField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('approve_byId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cashierId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Complaint_cashier_Id', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Complaint_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Complaint_last_modified_by', to=settings.AUTH_USER_MODEL)),
                ('shopId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops1.shopmodel')),
            ],
        ),
    ]
