# Generated by Django 4.2.6 on 2023-12-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_api', '0004_alter_collectionmode_upload_image_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='collections_status',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
