# Generated by Django 4.2.6 on 2024-01-02 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection_api', '0005_collection_collections_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='collection',
            table='Collection',
        ),
        migrations.AlterModelTable(
            name='collectionmode',
            table='CollectionMode',
        ),
        migrations.AlterModelTable(
            name='complaint',
            table='Complaint',
        ),
        migrations.AlterModelTable(
            name='skipshop',
            table='SkipShop',
        ),
    ]
