# Generated by Django 4.2.6 on 2023-12-13 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='user_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.userrole'),
        ),
    ]
