# Generated by Django 4.2.6 on 2024-01-02 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_usermodel_user_role'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermodel',
            table='UserModel',
        ),
        migrations.AlterModelTable(
            name='userrole',
            table='UserRole',
        ),
    ]
