# Generated by Django 4.2.6 on 2024-01-01 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRunning',
            fields=[
                ('vehicle_running_id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(null=True)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=20, null=True)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=20, null=True)),
                ('kilometer', models.DecimalField(decimal_places=5, max_digits=10)),
                ('status', models.CharField(blank=True, max_length=5, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='VehicleRunning_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='VehicleRunning_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('driverId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='VehicleRunning_last_modified_by', to=settings.AUTH_USER_MODEL)),
                ('vehicleId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle2.vehicle')),
            ],
        ),
    ]
