# Generated by Django 4.2.6 on 2024-01-01 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopProductRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_request_date_time', models.DateTimeField(null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('status', models.CharField(default='Rejected', max_length=100)),
                ('delivery_date_time', models.DateTimeField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ShopProductRequest_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ShopProductRequest_deleted', to=settings.AUTH_USER_MODEL)),
                ('driverId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ShopProductRequest_last_modified', to=settings.AUTH_USER_MODEL)),
                ('productId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops1.productmaster')),
                ('shopId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops1.shopmodel')),
            ],
        ),
    ]
