# Generated by Django 4.2.6 on 2024-01-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops1', '0002_shopproductrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrecieve',
            name='delete_reason',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
